CHANGELOG.md, Toolkit/Public/Get-RscMssqlInstance.ps1, Toolkit/Public/New-RscMssqlSnapshot.ps1, Toolkit/Public/Start-RscManagedVolumeSnapshot.ps1, Toolkit/Public/Stop-RscManagedVolumeSnapshot.ps1
I updated the help to 3 cmdlets so they can be clear on how to execute them based on jira tickets we received.
=> Update to help of 3 cmdlets

CHANGELOG.md
=> messing around

Toolkit/Public/New-RscMssqlExport.ps1
New-RscMssqlExport.ps1 had some old text for the help content. I have fixed the help text to be accurate to the parameters being submitted.
=> Updated Help text for cmdlet

Toolkit/Public/Remove-RscSla.ps1, Toolkit/Public/Resume-RscSla.ps1, Toolkit/Public/Suspend-RscSla.ps1
This change will allow users to pipe the result of Get-RscSla cmdlet to Suspend, Resume, and Remove RscSla cmdlets.
=> Add pipe support for SLA Cmdlets

Tests/unit/Import.Tests.ps1
- Test to make sure exported command list is the same on PowerShell 7 and PowerShell 5
=> Test to make sure exported command list is the same on PowerShell 5 and PowerShell 7

CHANGELOG.md, Toolkit/Public/Get-RscSla.ps1
- Get-RscSla using -Id parameter workaround. Now returns Name and Id.
- Get-RscSla now properly populates the protected object count.
=> Get-RscSla fixes

CHANGELOG.md, Toolkit/Public/Get-RscMssqlAvailabilityGroup.ps1, Toolkit/Public/Get-RscMssqlDatabase.ps1, Toolkit/Public/Get-RscMssqlInstance.ps1
- Fix to Get-RscMssqlInstance to address Issue #79
- Fix to Get-RscMssqlInstance to address Issue #73
- Fix to Get-RscMssqlDatabase to address Issue #75
- Fix to Get-RscMssqlDatabase to address Issue #77
- Fix to Get-RscMssqlAvailabilityGroup to address Issue #74
=> Fix to address multiple issues. 

CHANGELOG.md, Toolkit/Public/Get-RscMssqlDatabase.ps1, Toolkit/Public/Get-RscMssqlLogShipping.ps1
PR to address
- Issue #96  
- Issue #86
=> Pull Request to address issues

Toolkit/Public/Get-RscMssqlDatabase.ps1
Fix to allow for pulling back all databases on an instance
=> Fix to allow for pulling back all databases on an instance

CHANGELOG.md, RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/RubrikSecurityCloud.psd1, Toolkit/Format/NutanixVm.Format.ps1xml, Toolkit/Public/Get-RscNutanixVm.ps1, Toolkit/Public/Register-RscRubrikBackupService.ps1
- Get-RscNutanixVm - New cmdlet to get Nutanix VMs
- Register-RscRubrikBackupService - New cmdlet to register RBS on VMs
=> Get-RscNutanixVm and Register-RscRubrikBackupService

CHANGELOG.md, RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/RubrikSecurityCloud.psd1, Toolkit/Format/Permission.Format.ps1xml, Toolkit/Format/Role.Format.ps1xml, Toolkit/Public/Get-RscPermission.ps1, Toolkit/Public/Get-RscRole.ps1, Toolkit/Public/Merge-RscPermission.ps1, Toolkit/Public/New-RscPermission.ps1, Toolkit/Public/Set-RscRole.ps1
New cmdlets
* Get-RscRole - Retrieves RSC Roles
* New-RscPermission - Creates a new Rsc Permission for use in a role
* Merge-RscPermission - Merges a permission object into a role
* Set-RscRole - Overwrites a role in RSC with a role object
=> Role cmdlets and formatting

Toolkit/Public/Get-RscSla.ps1, Toolkit/Public/New-RscSla.ps1
- New-RscSla now has same parameters as Set-RscSla (Archival specs, etc)
- Get-RscSla now takes name as position 0 parameter
- Fixed weekly schedule missing from query
=> added parameters to New-RscSla, SLA name parameter position 0

Toolkit/Public/Get-RscPermission.ps1, Toolkit/Public/Get-RscSla.ps1
Fix Get-RscSla, remove mandatory operation argument from Get-RscPermission
=> 1.5 bugfixes

Toolkit/Public/Get-RscOrganization.ps1, Toolkit/Public/Get-RscPermission.ps1, Toolkit/Public/Merge-RscPermission.ps1
Get-RscPermission:
* should not require operation
* replace mandatory requirement on role parameter
=> Get-RscPermission fixes

Toolkit/Format/Snappable.Format.ps1xml, Toolkit/Public/Get-RscWorkload.ps1, Toolkit/Tests/e2e/Get-RscWorkload.Tests.ps1
- Get-RscWorkload - Added New Parameter `-ComplianceTimeRange` to get compliance status for a specific time
=> Get-RscWorkload updates

.github/workflows/runner.yml
https://rubrik.atlassian.net/browse/SPARK-422108
=> migrate GitHub managed runner to an internal one

.github/workflows/build_secrets.yml
https://rubrik.atlassian.net/browse/SPARK-422112
=> update workflow to retrieve secret from SA or vault

.github/workflows/service_account.yml
update workflow yml to prevent running when a PR is submitted by a non-Rubrik person
https://rubrik.atlassian.net/browse/SPARK-422113
=> retrieve SA from workflow params

Toolkit/Format/PhysicalHost.Format.ps1xml, Toolkit/Format/WindowsCluster.Format.ps1xml, Toolkit/Public/Get-RscMssqlInstance.ps1, Toolkit/Tests/e2e/Get-RscMssqlInstance.Tests.ps1
Fix Get-RscMssqlInstance fields to account for API changes, fixed tests, added tests
=> Fix Get-RscMssqlInstance

Toolkit/Public/Get-RscCluster.ps1
=> Minor edits to docs

Toolkit/Tests/e2e/Get-RscMssqlInstance.Tests.ps1
[SPARK-561105]
[SPARK-561105]: https://rubrik.atlassian.net/browse/SPARK-561105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: skip cluster filter test if no cluster object
