rubrikinc/rubrik-powershell-sdk

- Toolkit/Public/Protect-RscSnappable.ps1
Protect-RscSnappable adds any RSC snappable object to an SLA domain. It supports pipeline input, as well as inputObject for bulk SLA assignment.
> Add Protect-RscSnappable cmdlet

- CHANGELOG.md
- RubrikSecurityCloud/RubrikSecurityCloud.Client/GraphQLClient.cs
Removes code related to aliases, as aliases are not sufficient to handle field name conflicts, and
it is introducing a serialization bug for responses from RSC.
Test Plan:
1. run unit tests
2. verify that the bug is not happening anymore for APIs
that it was occurring for previously
> Fix serialization of GraphQL responses

- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/Cmdlets/Get-RscSnapshot.cs
While debugging an [issue](https://rubrik.atlassian.net/browse/SPARK-355688) I got confused due to conflicting names in RSC spark UI and our powershell SDK.
So the [Get-RscSnapshot](https://github.com/rubrikinc/rubrik-powershell-sdk/blob/5b5fa89f3e9908fe98facc1501b4220d0bd46bc1/RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/Cmdlets/Get-RscSnapshot.cs) uses the operation name as SnapshotListQuery but it should be SnapshotOfASnappableConnection . There is another SnapshotListQuery operation in the UI code which basically gets some information from hierarchyObjects.
So I confused both of them and also the owner of both these APIs were different (Platform and DLC). I guess we should update the operation name in the powershell cmdlet.
This will help us get rid of this confusion and also …
> Update the operation name for SnapshotListQuery

- CHANGELOG.md
- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/Private/RscTypeInitializer.cs
This is a bugfix for Get-RscType where -InitialProperties only initialized the first requested property of a nested property tree as described in [Issue-112](https://github.com/rubrikinc/rubrik-powershell-sdk/issues/112)
> Fix Issue-112 Get-RscType nested fields.

- CHANGELOG.md
- RubrikSecurityCloud/RubrikSecurityCloud.Client/GraphQLClient.cs
- RubrikSecurityCloud/RubrikSecurityCloud.Client/GraphQLInterfaceConverter.cs
- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/Cmdlets/Connect-Rsc.cs
- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/Cmdlets/Disconnect-Rsc.cs
- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/Private/RscBasePSCmdlet.cs
- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/Private/RscLogger.cs
- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/RubrikSecurityCloud.psd1
When an access token is expired, the SDK renews it - but does not store it in the PowerShell session , so the next cmdlet calls will all renew the token too.
> Access token renewal is not stored in PowerShell session

- RubrikSecurityCloud/RubrikSecurityCloud.Client/GraphQLClient.cs
- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/Cmdlets/New-RscQuery.cs
- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/Private/RscGqlPSCmdlet.cs
- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/Private/RscQuery.cs
When creating a query with New-RscQuery and calling it with Invoke() , any -Debug or -Verbose parameter passed to the cmdlet is lost when reaching the Invoke()'s sub-session
JIRA Issues:
https://rubrik.atlassian.net/browse/SPARK-395332
> Enable logging in PowerShell sub-sessions

- CHANGELOG.md
- Toolkit/Public/Get-RscVmwareVm.ps1
New Features: 
- Get-RscVmwareVm now takes a cluster object via pipeline. e.g. `Get-RscCluster "foo" | Get-RscVmwareVm`
- Add snapshotconsistencylevel to vSphereVM fields that are fetched from API.
Fixes:
- Corrected the -Relic switch in Get-RscVmwareVm to properly filter on relic status.
> Get-RscVmwareVm updates

- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/Cmdlets/Get-RscFileset.cs
- Tests/e2e/Get-RscFileset.Tests.ps1
Implementation in Get-RscFileSet does not properly fill in the nested query about Host Ids.
> Get-RscFileSet : fix arg assignment in nested query

- Utils/Get-RscSdkVersion.ps1
- Utils/Test-RscSdkRelease.ps1
This script is necessary for the SDK Release pipeline.
https://rubrik.atlassian.net/browse/SPARK-426610
Script's help message:
ADMIN USE ONLY. Test if the SDK is released correctly. (No-op if run as non-admin.)
ADMIN USE ONLY. (No-op if run as non-admin.)
This script tests if the SDK is released correctly.
The latest published version on The PowerShell Gallery must match:
- The SDK module version on the main branch.
- The latest version tag in the CHANGELOG.md file on the main branch.
- The latest release tag on the GitHub repository.
The published SDK version as a string (example: "1.9") if all
checks pass successfully. Otherwise, an empty string is returned.
> Test-RscSdkRelease

- Toolkit/Public/Get-RscNasSystem.ps1
- Toolkit/Tests/e2e/Get-RscNasSystem.Tests.ps1
The updated Get-RscNasSystem command will have
following functionality.
1. Get-RscNasSystem should return all NAS systems from the API. (Max Page size is 50)
2. Get-RscNasSystem -id "12345..." should return the NAS system with the specified ID.
3. Get-RscNasSystem -name "foo" should filter on NAS systems with the name of “foo” (Max Page size is 50)
4. Get-RscNasSystem -first 3 should return first 3 NAS systems
5. Get-RscNasSystem -name “foo” -first 3 should return first 3 NAS systems with name “foo”
Conducted manual testing by invoking Get-RscNasSystem for various scenarios.
Testing Doc: [link](https://docs.google.com/document/d/1ahwnPIp24BM5np4eSIa2Gj0Ewnma3gdTRtDLSQySsKM/edit?tab=t.0)
SPARK-439652
NA
> Get-RscNasSystem: Remove forced requirement of -id

- Toolkit/Public/Get-RscVmwareVm.ps1
- Toolkit/Tests/e2e/Get-RscVmwareVm.Tests.ps1
Missing `[0]` in field selection caused query execution to fail.
> fix: Get-RscVmwareVm missing [0] before cluster

- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/docs/GenerateDocs.ps1
**Note:** It includes `13 spaces` in the 
beginning of the codeblock and
includes `tab`
- PlatyPS don't allow tabs in
markdown, also mentioned [here](https://github.com/PowerShell/platyPS/blob/c7cd89b1c59b366b935d8e80de36815be6c00eec/docs/developer/platyPS/platyPS.schema.md?plain=1#L11)
- Replacing tab with 4 or 6 spaces is 
working fine but giving issue with 
2 spaces.
- More than 12 leading spaces in a line is creating issue
- Original Code includes 13 spaces in the beginning. 
- Tried with 12 and less (succeeding)
- Tried With 13 and 14 (failing)
Replaced tabs with 4 spaces and removed 
the first leading space from each line.
DotNet Build succeeded with successful 
docs generation.
SPARK-410830
NA
> Fix GenerateDocs Issue for Pwsh Cmdlets

- Toolkit/Public/Set-RscSla.ps1
- Toolkit/Tests/e2e/Set-RscSla.Tests.ps1
Previously, our tests used existing SLAs 
from the testing environment, which led
to unpredictable results. Now, this PR 
changes things up by creating a new SLA, 
running the test scenarios, 
and then cleaning it up afterwards. 
This way, our tests are more reliable 
with predictable behaviour.
- Test completed successfully
[SPARK-462879](https://rubrik.atlassian.net/browse/SPARK-462879)
NA
> Fix Set-RscSla e2e Test

- Toolkit/Tests/e2e/Get-RscNasShare.Tests.ps1
- Earlier `nasShares` query wansn't exposed publically, probably while
jira creation, schema for rubrik-inc
pwsh repo wasn't updated with latest
one, hence it failed with jira
tagged error.
- Verfied that `New-RscQueryNas.cs` now contains `Shares` subcommand.
- Also noted, UT testing all NasShares for a given NasSystem, failed because of
comparison with invalid NasShares
(with $null ids). Have
updated the test to ignore
comparison of such NasShares.
Test Ran successfully
[SPARK-462873](https://rubrik.atlassian.net/browse/SPARK-462873)
NA
> Fix Get-RscNasShare e2e test

- RubrikSecurityCloud/RubrikSecurityCloud.Client/RubrikSecurityCloud.Client.csproj
- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/LoadModule.psm1
- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/RubrikSecurityCloud.PowerShell.csproj
- Utils/_Build-RscSdk.ps1
This PR does following
- Removes `CVE-2024-43485` vulnerability from the RubrikSecurityCloud Client module by
updating the System.Text.JSON package to
version `8.0.5`.
- Upgrades the target runtime of the RubrikSecurityCloud PowerShell module to `net462`
[SPARK-473776](https://rubrik.atlassian.net/browse/SPARK-473776)
[SPARK-432214](https://rubrik.atlassian.net/browse/SPARK-432214)
[SPARK-473769](https://rubrik.atlassian.net/browse/SPARK-473769)
**`make` logs before changes**
**`make` logs after changes**
NA
> Upgrade .Net Module Configs to remove warnings

- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/LoadModule.psm1
- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/RubrikSecurityCloud.PowerShell.csproj
- Utils/_Build-RscSdk.ps1
The PR reverts net461 upgrade to 
net462 done by [this](https://github.com/rubrikinc/rubrik-powershell-sdk/pull/175) PR, 
since it's breaking with `pwsh-5.1` 
By reverting target-version to net461, 
basic commands are succeeding. 
[SPARK-483375](https://rubrik.atlassian.net/browse/SPARK-483375)
> Revert pwsh runtime upgrade

- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/LoadModule.psm1
- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/RubrikSecurityCloud.PowerShell.csproj
- Toolkit/Public/Get-RscNasShare.ps1
- Toolkit/Public/Get-RscOrganization.ps1
- Toolkit/Public/Get-RscSla.ps1
- Toolkit/Tests/e2e/Get-RscNasShare.Tests.ps1
- Toolkit/Tests/e2e/Get-RscNasSystem.Tests.ps1
- Utils/_Build-RscSdk.ps1
This PR contains following. 
- Upgrade of net461 to net481
- Since net481 doesn't detect 
path of assembly `System.Text.Json 8.0.5` 
in pwsh5, forcefully resolving it in `LoadModule.ps1`
- Fixes for toolkit scripts, 
failing in pwsh-5 due to recently 
discovered types-casting issues.
> net481 toolkit scripts fixes

- Toolkit/Public/Get-RscArchivalLocation.ps1
- Toolkit/Public/Get-RscAzureNativeVm.ps1
- Toolkit/Public/Get-RscCloudNativeTagRule.ps1
- Toolkit/Public/Get-RscCluster.ps1
- Toolkit/Public/Get-RscDb2Instance.ps1
- Toolkit/Public/Get-RscManagedVolume.ps1
- Toolkit/Public/Get-RscMssqlLiveMount.ps1
- Toolkit/Public/Get-RscOracleHost.ps1
- Toolkit/Public/Get-RscSapHanaSystem.ps1
- Toolkit/Public/New-RscMssqlSnapshot.ps1
This PR fixes existing bugs in toolkit cmdlets. 
Following is the brief for the same. 
- Get-RscArchivalLocation
As a solution have removed `-Id` filter, as it's also not mentioned in example.
- Get-RscCloudNativeTagRule 
- Get-RscOracleHost
- Get-RscAzureNativeVm
- All Parameters (-Id, -NameSubstring and -EffectiveSlaIds) were wrongly set. 
- Get-RscCloudNativeTagRule
- `$query.var.filters = @()` at line 75 wrongly set. It should be `filter` not `filters`
- Id Parameter doesn't specify query in `New-RscQuery -GqlQuery`
- Get-RscCluster
- Id filter logic was incorrect and it wasn't working as expected.
- Get-RscDb2Instance
- Id filter logic was incorrect and it wasn't working as expected.
- Get-RscManagedVolume
- RscCluster parameter had issue
- Get-RscMssqlLiveMount
- `RscMssqlDatabase` …
> Toolkit cmdlet fixes

- Toolkit/Public/New-RscSlaArchivalSpecs.ps1
In pwsh5  `$slaArchivalSpecs.ArchivalLocationToClusterMapping += $archivalLocationToClusterMapping` is giving following error 
```
Not able to convert System.Object[] to `RubrikSecurityCloud.Types.ArchivalLocationToClusterMappingInput`
```
Found out that it's happening for the scenarios where right side assignment is list of single object. `add` method is working fine here. 
Although, I was not able to replicate this issue outside of SDK.
> New-RscSlaArchivalSpecs Pwsh5 Fix

- Toolkit/Tests/e2e/Get-RscOrganization.Tests.ps1
This PR fixes e2e test for 
Get-RscOrganization Toolkit Cmdlet. 
The test expects was expecting one
object from `-Name` parameter, 
but it can yield multiple since 
it doesn't check for exact name 
but substring.
**Test succeeds on pwsh-7**
**Test succeeds on pwsh-5 on windows**
[SPARK-507940](https://rubrik.atlassian.net/browse/SPARK-507940)
> Fix get rscorganization test

- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/Private/RscGqlPSCmdlet.cs
- Tests/unit/EmptyProfile.Tests.ps1
- Earlier For Empty Field profile 
the codebase was changing field-profile 
to `DEFAULT`, since it's not 
expected behaviour, it's removed. 
Also put a check if no field profile 
is set then exception will be thrown.
- Added UTs so as to prevent 
regression in future.
[SPARK-498279](https://rubrik.atlassian.net/browse/SPARK-498279)
- Added UTs to test Empty Field Profile 
- Performed Manual Tests
**With `Empty` FieldProfile and adding fields using AddField parameter**
**With `Empty` FieldProfile and adding fields to the query**
**With Empty FieldProfile and without adding any fields**
> Fixed Empty Profile

- Toolkit/Public/Get-RscSla.ps1
- Toolkit/Public/Get-RscWorkload.ps1
`Get-RscSla` and `Get-RscWorkload` 
toolkit cmdlet creates query 
with `EMPTY` profile and directly 
access `query.Field.Nodes[0]` 
attribute since `Nodes` will 
not be set in `EMPTY` Profile, 
it will throw error. 
Earlier `EMPTY` profile had 
behaviour similar to `DEFAULT` profile. 
In order to ensure that customer don't 
get any behaviour change, making 
query with  `DEFAULT` 
field profile in these two cmdlets
**Build and Tests succeeded in pwsh5**
**Build and Tests succeeded in pwsh7**
[SPARK-498279](https://rubrik.atlassian.net/browse/)
> Fix failing tests because of EMPTY field profile

- Toolkit/Public/Start-RscManagedVolumeSnapshot.ps1
- Toolkit/Public/Stop-RscManagedVolumeSnapshot.ps1
This PR removes `-RscSnapshotId` field 
from `Start-RscManagedVolumeSnapshot` 
and `Stop-RscManagedVolumeSnapshot` cmdlet. 
The `RscSnapshotId` field excepts input to 
be passed to it, that we are not passing 
currently and since the DEFAULT FieldProfile 
include it, we need 
to explicitly remove it.
This change will remove following cmdlet error
```
Field 'rscSnapshotId' argument 'input' of type
| 'EndManagedVolumeSnapshotInput!' is required but not provided.
```
**`Start-RscManagedVolumeSnapshot` manually tested**
**`Stop-RscManagedVolumeSnapshot` manually tested**
Here we are getting expected err-message. It's not a failure.
`No inflight snapshot exists for managed volume ManagedVolume:::c0aec986-ff3e-4033-bb79-10f96a6cbfb7`
[SPARK-496743](https://rubrik.atlassian.net/browse/SPARK-49674 …
> Fix Start Stop Rsc Managed Volume Snapshot

- RubrikSecurityCloud/RubrikSecurityCloud.PowerShell/docs/GenerateDocs.ps1
Skipping `New-RscQueryAzureNative` to unblock release. 
Created Jira for this [here](https://rubrik.atlassian.net/browse/SPARK-517965)
> Skip GenDocs for `New-RscQueryAzureNative`

- CHANGELOG.md
- Toolkit/Public/Get-RscSnapshot.ps1
- Toolkit/Public/Protect-RscWorkload.ps1
- Toolkit/Tests/e2e/Get-RscSnapshot.Tests.ps1
- Get-RscSnapshot now retrieves snapshots for MSSQL databases. MSSQL database snapshots are tied to the DAG ID, not the ID of the object. Pipeline support now works with Get-RscMssqlDatabase:
```
Get-RscMssqlDatabase -Name "example" -Relic:$false -Replica:$false | Get-RscSnapshot
```
- Protect-RscWorkload now works with MSSQL databases. MSSQL database protection is tied to the DAG ID, not the ID of the object.
```
Get-RscMssqlDatabase -Name "example" -Relic:$false -Replica:$false | Protect-RscWorkload -Sla (Get-RscSla Bronze)
```
> MSSQL object handling for Get-RscSnapshot

- Toolkit/Tests/e2e/Get-RscAwsNativeEc2Instance.Tests.ps1
- Toolkit/Tests/e2e/Set-RscSla.Tests.ps1
Set-RscSla Test was failing 
due to assertion of `SnapshotScheduleLastUpdatedAt` 
field. It will get updated every time update happen, 
so asserting this field can make it falky. 
Hence skipping this assertion.
`Get-RscAwsNativeEc2Instance` 
was asserting `Get-RscAwsNativeEc2Instance` 
to return non empty-list. Changed the assertion to check for `don't throw`
Manual test-run succeded. 
[SPARK-535334](https://rubrik.atlassian.net/browse/SPARK-535334)
NA
> Fix pwsh sdk failing tests 

- RubrikSecurityCloud/RubrikSecurityCloud.Common/Config.cs
- RubrikSecurityCloud/RubrikSecurityCloud.Common/FragmentFactory.cs
[PR59287](https://github.com/scaledata/sdmain/pull/59287/files#diff-3194e54f980e15d769a0320d1779103a6c4afd59e9b908fad206b781205f8bd2) introduced two 
new fields cdmPendingObjectPauseAssignment 
and rscPendingObjectPauseAssignment which 
is behind OBJECT_PROTECTION_PAUSE FF, 
backend-work for this is not yet completed 
so it will not go GA for quite some time i guess. 
This is causing SDK tests to fail, because 
these fields are getting included in some 
cmdlets by default.
This PR is skipping these fields from consumption.
Also created [SPARK-548179](https://rubrik.atlassian.net/browse/SPARK-548179) to unskip 
these fields once it reaches GA.
- SDK Tests Run
[SPARK-548620](https://rubrik.atlassian.net/browse/SPARK-548620)
> Skip non ga fields

- RubrikSecurityCloud/RubrikSecurityCloud.Client/GraphQLClient.cs
On [this](https://rubrikinc.slack.com/archives/C053UBHTBUH/p1742266198740229) slack thread we are seeing 
that customer is getting 
`Object reference not set to an instance of an object.` 
error occassionally while executing 
`vSphereVmNewConnection`.
Found out that it's happening 
because we are not doing 
exception handling properly, 
which is fixed in this PR.
Tried throwing exception, and 
replicated the situation that customer is getting.
Error while executing. 
Now fixed it by proper error-handling, 
executing pwsh command now 
give proper exception.
> Fix GraphQLClient.cs Exception Handling
